### ISSUE TITLE
Neuron-PT-Lightning: Issues when trying to train a simple MLP

### ISSUE THREAD

**Issue by sgaseretto** [aws-neuron/neuronx-distributed#22]
# Issue: Training on AWS Trainium Failing

I'm encountering issues when trying to train certain architectures on AWS Trainium. Initially, we attempted to migrate our code from a BERT model, fully implemented on PyTorch Lightning, to Neuron based on the current available documentation ([link](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/neuronx-distributed/ptl_developer_guide.html?highlight=NeuronLTModule)). And we are running our tests on the following docker [images](https://github.com/aws-neuron/deep-learning-containers):
- `1.13.1-neuronx-py310-sdk2.18.2-ubuntu20.04`
- `2.1.2-neuronx-py310-sdk2.18.2-ubuntu20.04`

To further test, I switched the model architecture to an MLP and defined a Datamodule to train it on MNIST. I'm encountering the same errors as when I was trying to train the BERT model. Below is the code for reproduction:

```python
import torch
import torch.nn.functional as F
import torchvision.datasets as datasets
import torchvision.transforms as transforms
from torch import nn, optim
from torch.utils.data import DataLoader
from tqdm import tqdm
from torch.utils.data import random_split
import pytorch_lightning as pl 
import torchmetrics 
from torchmetrics import Metric

from pytorch_lightning.callbacks import ModelCheckpoint
from pytorch_lightning import Trainer, LightningDataModule

# import pytorch_lightning as lightning

# NDX Imports
from neuronx_distributed.lightning import (
    NeuronLTModule,
    NeuronTensorBoardLogger,
    NeuronXLAPrecisionPlugin,
    NeuronXLAStrategy,
    NeuronTQDMProgressBar
)
import neuronx_distributed.parallel_layers.parallel_state as parallel_state
import neuronx_distributed as nxd
from neuronx_distributed import initialize_parallel_optimizer
import torch_xla.core.xla_model as xm

# XLA imports
import torch_xla.core.xla_model as xm
# XLA imports for parallel loader and multi-processing
import torch_xla.distributed.parallel_loader as pl
import torch_xla.distributed.xla_multiprocessing as xmp
from torch.utils.data.distributed import DistributedSampler

import numpy as np

class MyAccuracy(Metric):
    def __init__(self):
        super().__init__()
        self.add_state("total", default=torch.tensor(0), dist_reduce_fx="sum")
        self.add_state("correct", default=torch.tensor(0), dist_reduce_fx="sum")

    def update(self, preds, target):
        preds = torch.argmax(preds, dim=1)
        assert preds.shape == target.shape
        self.correct += torch.sum(preds == target)
        self.total += target.numel()

    def compute(self):
        return self.correct.float() / self.total.float()


# class NNManualOpt(pl.LightningModule):
class NNManualOpt(NeuronLTModule):
    def __init__(self, input_size, num_classes, *args, **kwargs):
        # super().__init__()
        super().__init__(*args, **kwargs)
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)
        self.loss_fn = nn.CrossEntropyLoss()
        self.accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)
        self.my_accuracy = MyAccuracy()
        self.f1_score = torchmetrics.F1Score(task="multiclass", num_classes=num_classes)

        # manual opt
        self.automatic_optimization = False

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

    def training_step(self, batch, batch_idx):
        xm.mark_step() # Isolate forward+backward graph
        optimizer = self.optimizers()
        scheduler = self.lr_schedulers()

        x, y = batch 
        x = x.reshape(x.size(0), -1)
        scores = self.forward(x)
        loss = self.loss_fn(scores, y)
        
        # Manual optimization
        optimizer.zero_grad()
        self.manual_backward(loss)
        xm.mark_step() # Isolate forward+backward graph
        optimizer.step()
        scheduler.step(loss)

        accuracy = self.my_accuracy(scores, y) 
        f1_score = self.f1_score(scores, y)
        self.log_dict({'train_loss': loss, 'train_accuracy': accuracy, 'train_f1_score': f1_score},
                      on_step=False, on_epoch=True, prog_bar=True)
        xm.mark_step() # Isolate Optimization step graph
        return loss 
    
    def configure_optimizers(self):
        optimizer = initialize_parallel_optimizer(
            nxd_config=self.nxd_config, 
            optimizer_class=self.opt_cls,
            parameters=self.parameters,
            **self.opt_kwargs
        )
        optimizer.zero_grad()
        scheduler = self.scheduler_cls(
            optimizer=optimizer,
            **self.scheduler_kwargs
        )
        return {
            [optimizer],
            [
                {
                    "scheduler":scheduler,
                }
            ]
        }


# class MnistDataModule(pl.LightningDataModule):
class MnistDataModule(LightningDataModule):
    def __init__(self, data_dir, batch_size, num_workers):
        super().__init__()
        self.data_dir = data_dir 
        self.batch_size = batch_size
        self.num_workers = num_workers

    def prepare_data(self):
        datasets.MNIST(self.data_dir, train=True, download=True)
        datasets.MNIST(self.data_dir, train=False, download=True)

    def setup(self, stage):
        entire_dataset = datasets.MNIST(
            root=self.data_dir, 
            train=True,
            transform=transforms.ToTensor(),
            download=False,
        )
        self.train_ds, self.val_ds = random_split(entire_dataset, [50000, 10000])
        self.test_ds = datasets.MNIST(
            root=self.data_dir,
            train=False,
            transform=transforms.ToTensor(),
            download=False,
        )

    def train_dataloader(self):
        return DataLoader(
            self.train_ds,
            batch_size=self.batch_size,
            num_workers=self.num_workers,
            shuffle=True,
        )


class CosineDecayLinearWarmupScheduleVanilla(optim.lr_scheduler.LambdaLR):
    """Cosine decay with linear warmup schedule."""

    def __init__(
        self,
        total_steps: int,
        optimizer: torch.optim.Optimizer,
        warmup_steps: int,
        last_epoch: int = -1,
    ):
        """Initialize a cosine decay with linear warmup schedule.
        Args:
            optimizer: Wrapped optimizer.
            warmup_steps: Linear warmup steps.
            last_epoch: The index of last epoch. Default: -1.
        """
        self.total_steps = total_steps
        self.warmup_steps = warmup_steps
        super().__init__(optimizer, lr_lambda=self.lr_lambda, last_epoch=last_epoch)

    def lr_lambda(self, current_step: int) -> float:
        """Learning rate lambda function."""
        if current_step < self.warmup_steps:
            return current_step / self.warmup_steps
        else:
            e = current_step - self.warmup_steps
            es = max(self.total_steps - self.warmup_steps, 1)
            return 0.5 * (1.0 + np.cos(np.pi * e / es))


def get_lr_scheduler(optimizer, total_steps, warmup_steps):
    # return optim.lr_scheduler.ReduceLROnPlateau(
    #     optimizer, patience=4, factor=0.01, verbose=True
    # )
    return CosineDecayLinearWarmupScheduleVanilla(
        optimizer=optimizer,
        total_steps=total_steps,
        warmup_steps=warmup_steps
    )


def main():
    # Hyperparameters
    input_size = 784
    num_classes = 10
    learning_rate = 0.001
    batch_size = 64
    num_epochs = 5

    # Data Module
    dm = MnistDataModule(
        data_dir="dataset/", 
        batch_size=batch_size, 
        num_workers=10
    )
    # total of maxsteps
    dm.setup("fit")
    total_steps = len(dm.train_dataloader().dataset)

    # Model
    nxd_config = nxd.neuronx_distributed_config(
        optimizer_config= {"zero_one_enabled":False}
    )
    opt_cls = optim.AdamW
    scheduler_cls = get_lr_scheduler

    # model = NN(input_size=input_size, num_classes=num_classes)
    model = NNManualOpt(
        nxd_config=nxd_config,
        opt_cls= opt_cls,
        scheduler_cls=scheduler_cls,
        input_size=input_size, 
        num_classes=num_classes,
        opt_kwargs={"lr": 1e-3},
        scheduler_kwargs={
            "total_steps":total_steps,
            "warmup_steps":100
        }
    )

    # Trainer 
    strategy = NeuronXLAStrategy()
    callbacks = [NeuronTQDMProgressBar()]

    trainer = Trainer(
        max_epochs=num_epochs, 
        strategy=strategy,
        callbacks=callbacks,
        enable_checkpointing=True, 
        enable_progress_bar=True,
    )
    trainer.fit(model=model, datamodule=dm)

if __name__ == '__main__':
    main()
```

On both containers, we installed PyTorch Lightning 2.1.0 (not Lightning):
```
pip install pytorch-lightning==2.1.0
```

### Running on `1.13.1-neuronx-py310-sdk2.18.2-ubuntu20.04`
```bash
/opt/app/trainium/data/SRR4026033_1_Heavy_IGHG.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/ERR2843418_Heavy_IGHG.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR4026019_1_Heavy_IGHA.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR3106492_Heavy_Bulk.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR611801_1_Light_Bulk.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR3192715_Heavy_IGHA.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR5408010_Heavy_Bulk.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR4297312_Heavy_Bulk.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR4026030_1_Heavy_IGHG.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
/opt/app/trainium/data/SRR5471255_1_Light_Bulk.csv.gz
/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py:123: DataFrame.applymap has been deprecated. Use DataFrame.map instead.

Loaded OAS training dataset with 4464 samples. Took 0.06 seconds on rank None.

[2024-05-20 13:44:49.699: W neuronx_distributed/trainer/trainer.py:44] [rank_0_pp-1_tp-1_dp-1] grad_clipping is not set, automatically set it to True.
[2024-05-20 13:44:49.699: W neuronx_distributed/trainer/trainer.py:48] [rank_0_pp-1_tp-1_dp-1] max_grad_norm is not set, automatically set it to one.
Traceback (most recent call last):
  File "/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py", line 1032, in <module>
    training_lightning()
  File "/opt/app/trainium/src/lightning2neuron/mlm_neuron_lightning.py", line 1011, in training_lightning
    strategy = NeuronXLAStrategy(nxd_config=nxd_config)
  File "/usr/local/lib/python3.10/site-packages/neuronx_distributed/lightning/strategy.py", line 44, in __init__
    accelerator=NeuronXLAAccelerator(),
  File "/usr/local/lib/python3.10/site-packages/lightning_fabric/accelerators/xla.py", line 37, in __init__
    raise RuntimeError("The XLA XRT runtime is not supported anymore.")
RuntimeError: The XLA XRT runtime is not supported anymore.

```

### Running on `2.1.2-neuronx-py310-sdk2.18.2-ubuntu20.04`
``` bash
/usr/local/lib/python3.10/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 10 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
[2024-05-23 23:09:48.620: W neuronx_distributed/trainer/trainer.py:44] [rank_0_pp-1_tp-1_dp-1] grad_clipping is not set, automatically set it to True.
[2024-05-23 23:09:48.620: W neuronx_distributed/trainer/trainer.py:48] [rank_0_pp-1_tp-1_dp-1] max_grad_norm is not set, automatically set it to one.
GPU available: False, used: False
TPU available: False, using: 8 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
WARNING:root:Unsupported nprocs (8), ignoring...
WARNING:root:MASTER_ADDR not setting, defaulting to localhost
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'torch.nn.modules.linear.Linear'>: it's not the same object as torch.nn.modules.linear.Linear
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/app/trainium/src/lightning2neuron/mlp_ndx.py", line 252, in <module>
    main()
  File "/opt/app/trainium/src/lightning2neuron/mlp_ndx.py", line 249, in main
    trainer.fit(model=model, datamodule=dm)
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 545, in fit
    call._call_and_handle_interrupt(
  File "/usr/local/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/neuronx_distributed/lightning/launcher.py", line 49, in launch
    process_context = xmp.spawn(
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/distributed/xla_multiprocessing.py", line 38, in spawn
    return pjrt.spawn(fn, nprocs, start_method, args)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 202, in spawn
    run_multiprocess(spawn_fn, start_method=start_method)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/runtime.py", line 82, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 159, in run_multiprocess
    replica_results = list(
  File "/usr/local/lib/python3.10/site-packages/torch_xla/_internal/pjrt.py", line 160, in <genexpr>
    itertools.chain.from_iterable(
  File "/usr/local/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/usr/local/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'torch.nn.modules.linear.Linear'>: it's not the same object as torch.nn.modules.linear.Linear

```

**Comment by kvshbg-aws** [comment]
Hello @sgaseretto , can you kindly let us know which environment setup are you running the above mentioned training script on? Is it a ParallelCluster ([as defined here](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/general/devflows/training/parallelcluster/parallelcluster-training.html)) or is it EKS or something else? Can you also provide the bash script (if any) which you are using to launch the training jobs? If there are no scripts, then can you explain how you are running the job(s)? 

This will help us in better understanding of your issue and provide a solution. 
Thank you!

**Comment by sgaseretto** [comment]
Hello @kvshbg-aws. Since I'm testing this, I'm running it on a `trn1.x2large` using this [Hugging Face AMI](https://aws.amazon.com/marketplace/pp/prodview-gr3e6yiscria2?sr=0-1&ref_=beagle&applicationId=AWS-EC2-Console). I'm building images both for torch `1.13.1` and `2.1.2` with this dockerfile: 
```dockerfile
ARG NEURON_VER=2.18.2
ARG PY_VERSION=310
ARG PYTORCH_VER=2.1.2

# Use arguments to specify the base image
FROM public.ecr.aws/neuron/pytorch-training-neuronx:${PYTORCH_VER}-neuronx-py${PY_VERSION}-sdk${NEURON_VER}-ubuntu20.04

# Configure tensorboard for trn1
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt

WORKDIR /opt/app/trainium
```

With this `requirements.txt`:
```
jsonargparse[signatures]>=4.17.0
wandb
pandas
s3fs
sagemaker
pytorch-lightning==2.1.0
```

I'm launching those containers in an interactive mode, for example for torch `1.13.1` I named the image `nxd_torch1`:
```
docker run -it --device=/dev/neuron0 --name neuron_torch_v1 -v <folder path from host>:/opt/app/trainium/src nxd_torch1
```

And then I'm running the script with:
```
torchrun --nproc_per_node 2 mlp_train.py
```

**Comment by flamingofugang** [comment]
Hi @sgaseretto,

You can create a separate model and get_model() function:
```
class MLP(nn.Module):
    def __init__(self, input_size, num_classes):
        super().__init__()
        self.num_classes = num_classes
        self.fc1 = nn.Linear(input_size, 50)
        self.fc2 = nn.Linear(50, num_classes)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
def get_model(model_config):
    model = MLP(model_config["input_size"], model_config["num_classes"])
    return model
```

Then pass it to your implementation of NeuronLTModule class, which is NNManualOpt():
```
    model = NNManualOpt(
        model_fn=get_model,
        model_args=(model_config,),
        nxd_config=nxd_config,
        opt_cls= opt_cls,
        scheduler_cls=scheduler_cls,
        opt_kwargs={"lr": 1e-3},
        scheduler_kwargs={
            "total_steps":total_steps,
            "warmup_steps":100
        }
    )
```
It should work with torch 1.13.1

**Comment by sgaseretto** [comment]
Sorry for the late response, this issue was resolved. Thanks for the help
